anticipate/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('anticipatory-orders', views.showAntiOrders, name='anti_orders'),
    path('qwikvendor-dashboard/anticipatory-orders/', views.showQwikVendorAntiOrders, name='qwikvendor_anti_orders'),
    path('qwikvendor-dashboard/anticipatory-orders/update/<int:id>', views.updateQwikVendorAntiOrders, name='qwikvendor_update_anti_orders'),
    path('qwikpartner-dashboard/anticipatory-orders/', views.showQwikPartnerAntiOrders, name='qwikpartner_anti_orders'),
    path('qwika-dashboard/anticipatory-orders/', views.showQwikAdminAntiOrders, name='qwikadmin_anti_orders'),
    path('qwika-dashboard/sales-graph/', views.showQwikAdminSalesGraph, name='qwikadmin_sales_graph'),
    path('qwika-dashboard/anticipatory-credits/', views.showQwikAdminAntiCredits, name='qwikadmin_anti_credits'),
    path('qwika-dashboard/anticipatory-payments/', views.showQwikAdminAntiPayments, name='qwikadmin_anti_payments'),
    path('qwika-dashboard/anticipatory-sales/', views.showQwikAdminAntiSales, name='qwikadmin_anti_sales'),
    path('qwikpartner-dashboard/anticipatory-orders/update/<int:id>', views.updateQwikPartnerAntiOrders, name='qwikpartner_update_anti_order'),
    path('qwikpartner-dashboard/anticipatory-orders/payment-update/<int:id>', views.updateQwikPartnerAntiOrders3rd, name='qwikpartner_update_anti_order_3rd'),
    path('qwikpartner-dashboard/anticipatory-orders/invoice/<str:pk>/', views.showQwikPartnerAntiInvoice, name='show_partner_anti_invoice'),
    path('qwikvendor-dashboard/anticipatory-orders/invoice/<str:pk>/', views.showQwikVendorAntiInvoice, name='show_vendor_anti_invoice'),
    path('qwikcustomer-dashboard/anticipatory-orders/invoice/<str:pk>/', views.showAntiInvoice, name='show_anti_invoice'),
    path('qwikcustomer-dashboard/anticipatory-orders/invoice/unpaid/<str:pk>/', views.showAntiInvoiceUnPaid, name='show_anti_invoice_unpaid'),
    path('qwika-dashboard/anticipatory-orders/export-csv', views.exportCSVAntis, name='export_csv_anti'),
    path('qwika-dashboard/anticipatory-credits/export-csv', views.exportCSVCredits, name='export_csv_credit'),
    path('qwika-dashboard/anticipatory-payments/export-csv', views.exportCSVPayments, name='export_csv_payment'),
    path('qwika-dashboard/anticipatory-orders/randomized', views.randomize, name='qwikadmin_randomize'),
    # path('qwika-dashboard/anticipatory-orders/export-pdf', views.exportPDF, name='export_pdf'),
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/cartadd/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/cartremove/<product_id>/', views.cart_remove, name='cart_remove'),

]

households/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('adm/', admin.site.urls),
    path('', include('home.urls')),
    # path('', include('pictures.urls')),
    # path('', include('videos.urls')),
    # path('', include('news.urls')),
    # path('', include('articles.urls')),
    path('', include('users.urls')),
    path('', include(('products.urls', 'products'), namespace='products')),
    path('cart', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('anticipate.urls', 'anticipate'), namespace='anticipate')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views
from django.contrib.sitemaps.views import sitemap
from products.sitemaps import ProductSitemap

sitemaps={
    'products':ProductSitemap,
}

urlpatterns = [
    path('products', views.product_list, name='product_list'),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('<category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<id>/', views.product_detail, name='product_detail'),
    path('product/description/<id>/', views.product_detail2, name='product_detail2'),
    path('qwikvendor-dashboard/products/', views.showQwikVendorProducts, name='qwikvendor_products'),
    path('qwikpartner-dashboard/products/', views.showQwikPartnerProducts, name='qwikpartner_products'),
    path('qwikpartner-dashboard/cylinders-received-empty/', views.showQwikPartnerCylindersReceivedEmpty, name='qwikpartner_cylinders_received_empty'),
    path('qwikvendor-dashboard/cylinders-dispatched-to-plant/', views.showQwikVendorCylindersDispatchedToPlant, name='qwikvendor_cylinders_dispatched_to_plant'),
    path('qwikvendor-dashboard/cylinders-released-filled-to-qwikpartner/', views.showQwikVendorCylindersReleasedFilledToQwikPartner, name='qwikvendor_cylinders_released_filled_to_qwikpartner'),
    path('qwikpartner-dashboard/cylinders-dispatched-filled-to-qwikcustomer/', views.showQwikPartnerCylindersDispatchedFilledToQwikCustomer, name='qwikpartner_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwika-dashboard/cylinders-dispatched-filled-to-qwikcustomer/', views.showQwikAdminCylindersDispatchedFilledToQwikCustomer, name='qwikadmin_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwikpartner-dashboard/cylinders-dispatched-filled-to-qwikcustomer/accept/<int:id>', views.acceptQwikPartnerCylindersDispatchedFilledToQwikCustomer, name='accept_qwikpartner_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwikpartner-dashboard/cylinders-dispatched-filled-to-qwikcustomer/decline/<int:id>', views.declineQwikPartnerCylindersDispatchedFilledToQwikCustomer, name='decline_qwikpartner_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwika-dashboard/cylinders-dispatched-filled-to-qwikcustomer/accept/<int:id>', views.acceptQwikAdminCylindersDispatchedFilledToQwikCustomer, name='accept_qwikadmin_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwika-dashboard/cylinders-dispatched-filled-to-qwikcustomer/decline/<int:id>', views.declineQwikAdminCylindersDispatchedFilledToQwikCustomer, name='decline_qwikadmin_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwikpartner-dashboard/cylinders-dispatched-to-plant/', views.showQwikPartnerCylindersDispatchedToPlant, name='qwikpartner_cylinders_dispatched_to_plant'),
    path('qwikpartner-dashboard/cylinders-delivered-filled-to-qwiklet/', views.showQwikPartnerCylindersDeliveredFilledToQwikLet, name='qwikpartner_cylinders_delivered_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-delivered-filled-to-qwiklet/', views.showQwikVendorCylindersDeliveredFilledToQwikLet, name='qwikvendor_cylinders_delivered_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-delivered-filled-to-qwiklet/', views.showQwikAdminCylindersDeliveredFilledToQwikLet, name='qwikadmin_cylinders_delivered_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-delivered-filled-to-qwiklet/accept/<int:id>', views.acceptQwikAdminCylindersDeliveredFilledToQwikLet, name='accept_qwikadmin_cylinders_delivered_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-delivered-filled-to-qwiklet/decline/<int:id>', views.declineQwikAdminCylindersDeliveredFilledToQwikLet, name='decline_qwikadmin_cylinders_delivered_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-delivered-filled-to-qwiklet/accept/<int:id>', views.acceptQwikVendorCylindersDeliveredFilledToQwikLet, name='accept_qwikvendor_cylinders_delivered_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-delivered-filled-to-qwiklet/decline/<int:id>', views.declineQwikVendorCylindersDeliveredFilledToQwikLet, name='decline_qwikvendor_cylinders_delivered_filled_to_qwiklet'),
    path('qwikpartner-dashboard/cylinders-returned-filled-to-qwiklet/return/<int:id>', views.returnQwikPartnerCylindersReturnedFilledToQwikLet, name='return_qwikpartner_cylinders_returned_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-returned-filled-to-qwiklet/accept/<int:id>', views.acceptQwikVendorCylindersReturnedFilledToQwikLet, name='accept_qwikvendor_cylinders_returned_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-returned-filled-to-qwiklet/decline/<int:id>', views.declineQwikVendorCylindersReturnedFilledToQwikLet, name='decline_qwikvendor_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/accept/<int:id>', views.acceptQwikAdminCylindersReturnedFilledToQwikLet, name='accept_qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/decline/<int:id>', views.declineQwikAdminCylindersReturnedFilledToQwikLet, name='decline_qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/return/<int:id>', views.returnQwikAdminCylindersReturnedFilledToQwikLet, name='return_qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/not-return/<int:id>', views.notReturnQwikAdminCylindersReturnedFilledToQwikLet, name='not_return_qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/', views.showQwikAdminCylindersReturnedFilledToQwikLet, name='qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwikpartner-dashboard/cylinders-dispatched-to-plant/accept/<int:id>', views.acceptQwikPartnerCylindersDispatchedToPlant, name='accept_qwikpartner_cylinders_dispatched_to_plant'),
    path('qwikpartner-dashboard/cylinders-dispatched-to-plant/decline/<int:id>', views.declineQwikPartnerCylindersDispatchedToPlant, name='decline_qwikpartner_cylinders_dispatched_to_plant'),
    path('qwika-dashboard/cylinders-dispatched-to-plant/', views.showQwikAdminCylindersDispatchedToPlant, name='qwikadmin_cylinders_dispatched_to_plant'),
    path('qwika-dashboard/cylinders-dispatched-to-plant/accept/<int:id>', views.acceptQwikAdminCylindersDispatchedToPlant, name='accept_qwikadmin_cylinders_dispatched_to_plant'),
    path('qwika-dashboard/cylinders-dispatched-to-plant/decline/<int:id>', views.declineQwikAdminCylindersDispatchedToPlant, name='decline_qwikadmin_cylinders_dispatched_to_plant'),
    path('qwikpartner-dashboard/cylinders-delivered-to-qwikcustomer-anticipatory/', views.showQwikPartnerCylindersDeliveredToQwikCustomerAnti, name='qwikpartner_cylinders_delivered_to_qwikcustomer_anti'),
    path('qwikpartner-dashboard/cylinders-delivered-to-qwikcustomer/', views.showQwikPartnerCylindersDeliveredToQwikCustomerUser, name='qwikpartner_cylinders_delivered_to_qwikcustomer_user'),
    path('qwikvendor-dashboard/cylinders-delivered-to-qwikcustomer/', views.showQwikVendorCylindersDeliveredToQwikCustomerUser, name='qwikvendor_cylinders_delivered_to_qwikcustomer_user'),
    path('qwikvendor-dashboard/cylinders-delivered-to-qwikcustomer-anticipatory/', views.showQwikVendorCylindersDeliveredToQwikCustomerAnti, name='qwikvendor_cylinders_delivered_to_qwikcustomer_anti'),
    path('qwika-dashboard/cylinders-delivered-to-qwikcustomer-anticipatory/', views.showQwikAdminCylindersDeliveredToQwikCustomerAnti, name='qwikadmin_cylinders_delivered_to_qwikcustomer_anti'),
    path('qwika-dashboard/cylinders-delivered-to-qwikcustomer/', views.showQwikAdminCylindersDeliveredToQwikCustomerUser, name='qwikadmin_cylinders_delivered_to_qwikcustomer_user'),
    path('qwika-dashboard/cylinders-delivered-to-qwikcustomer/update/<int:id>', views.updateQwikAdminCylindersDeliveredToQwikCustomerUser, name='update_qwikadmin_cylinders_delivered_to_qwikcustomer_user'),
    path('qwika-dashboard/cylinders-delivered-to-qwikcustomer-anticipatory/update/<int:id>', views.updateQwikAdminCylindersDeliveredToQwikCustomerAnti, name='update_qwikadmin_cylinders_delivered_to_qwikcustomer_anti'),
    path('qwikcustomer-dashboard/cylinders-received-filled-anticipatory/', views.showQwikCustomerCylindersReceivedFilledAnti, name='qwikcustomer_cylinders_received_filled_anti'),
    path('qwikcustomer-dashboard/cylinders-received-filled/', views.showQwikCustomerCylindersReceivedFilledUser, name='qwikcustomer_cylinders_received_filled_user'),
    path('qwikpartner-dashboard/cylinders-returned-filled-to-qwiklet/', views.showQwikPartnerCylindersReturnedFilledToQwikLet, name='qwikpartner_cylinders_returned_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-returned-filled-to-qwiklet/', views.showQwikVendorCylindersReturnedFilledToQwikLet, name='qwikvendor_cylinders_returned_filled_to_qwiklet'),
    path('qwikpartner-dashboard/cylinders-returned-empty/', views.showQwikPartnerCylindersReturnedEmpty, name='qwikpartner_cylinders_returned_empty'),
    path('qwikvendor-dashboard/cylinders-returned-empty/', views.showQwikVendorCylindersReturnedEmpty, name='qwikvendor_cylinders_returned_empty'),
    path('qwikvendor-dashboard/cylinders-returned-empty/accept/<int:id>', views.acceptQwikVendorCylindersReturnedEmpty, name='accept_qwikvendor_cylinders_returned_empty'),
    path('qwikvendor-dashboard/cylinders-returned-empty/decline/<int:id>', views.declineQwikVendorCylindersReturnedEmpty, name='decline_qwikvendor_cylinders_returned_empty'),
    path('qwika-dashboard/cylinders-returned-empty/accept/<int:id>', views.acceptQwikAdminCylindersReturnedEmpty, name='accept_qwikadmin_cylinders_returned_empty'),
    path('qwika-dashboard/cylinders-returned-empty/decline/<int:id>', views.declineQwikAdminCylindersReturnedEmpty, name='decline_qwikadmin_cylinders_returned_empty'),

anticipate/models.py
from django.db import models
from products.models import Product
from users.models import Person

class AntiOrder(models.Model):
    PAYMENT_TYPE1 = [
		('Pay Now','Pay Now'),
	]
    PAYMENT_TYPE2 = [
		('Paylater', 'Paylater'),
	]
    PAYMENT_TYPE3 = [
        ('Pay Small Small', 'Pay Small Small'),
	]
    PAYMENT_CHOICES = [
		('Bank Transfer','Bank Transfer'),
		('PoS', 'PoS'),
        ('Cash', 'Cash'),
	]
    TRANSACTION_CHOICES = [
		('Open','Open'),
		('Closed', 'Closed'),
	]
    user = models.ForeignKey(Person, null=True, blank=True, on_delete=models.SET_NULL)
    order_Id = models.IntegerField(blank=True, null=True)
    cylinder = models.ManyToManyField('products.Product', related_name='anti_cylinders')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True, related_name='anti_products')
    category = models.CharField(max_length=12, blank=True, null=True)
    outlet_static = models.CharField(max_length=30, blank=True, null=True)
    who6_2 = models.CharField(max_length=9, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    payment_type1 = models.CharField(max_length=7, choices=PAYMENT_TYPE1, blank=True, null=True, verbose_name="Payment Type")
    payment_type2 = models.CharField(max_length=8, choices=PAYMENT_TYPE2, blank=True, null=True, verbose_name="")
    payment_type3 = models.CharField(max_length=15, choices=PAYMENT_TYPE3, blank=True, null=True, verbose_name="")
    payment_date_later = models.DateField(blank=True, null=True, verbose_name="Committed Payment Date")
    payment_split = models.CharField(max_length=40, blank=True, null=True, verbose_name="Payment Split in Amount")
    # payment_date_small = models.DateField(blank=True, null=True, verbose_name="Committed Payment Date")
    payment_choice = models.CharField(max_length=13, choices=PAYMENT_CHOICES, null=True, verbose_name="Payment Choice")
    payment_ref = models.CharField(max_length=40, blank=True, null=True, verbose_name="Payment Reference")
    payment1 = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True, null=True, verbose_name="1st Payment")
    payment1_date = models.DateField(blank=True, null=True, verbose_name="1st Payment Date")
    payment2 = models.DecimalField(max_digits=10,  decimal_places=2, blank=True, null=True, verbose_name="2nd Payment")
    payment2_date = models.DateField(blank=True, null=True, verbose_name="2nd Payment Date")
    payment3 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name="3rd Payment")
    payment3_date = models.DateField(blank=True, null=True, verbose_name="3rd Payment Date")
    payment_total = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True, null=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True, null=True)
    outlet = models.ForeignKey('users.Outlet', on_delete=models.SET_NULL, null=True, blank=True)
    stage = models.CharField(max_length=3, blank=True, null=True)
    transaction = models.CharField(max_length=12, choices=TRANSACTION_CHOICES, default='Open', blank=True, null=True, verbose_name="Transaction Status")


    static_price = models.DecimalField(max_digits=11, blank=True, null=True, decimal_places=2)
    static_total_cost = models.DecimalField(max_digits=13, default=0, blank=True, null=True, decimal_places=2)
    static_price2 = models.DecimalField(max_digits=11, blank=True, null=True, decimal_places=2)
    static_total_cost2 = models.DecimalField(max_digits=13, blank=True, null=True, decimal_places=2)
    # point = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{}'.format(self.id)

    def total_cost(self):
        if self.product.category.price == None:
            pass
        else:
            return self.product.category.price * self.quantity

templates/anticipate/anti_orders.html
{% extends 'board.html' %}
{% load static %}
{% load humanize %}
{% block title %}
  <title>Anticipatory Orders</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}
{% load home_tags %}
<div class=" app-content">
	<div class="side-app">
    <br>
    {% include 'partials/_alerts.html' %}
		<!--Page Header-->
		<div class="page-header">
			<h4 class="page-title"><i class="fa fa-spinner text-dark-green mr-2 fa-1x"></i>Welcome to your anticipatory orders' page, <strong class="text-dark-green">{{user.first_name}}</strong></h4>
			<ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a href="{% url 'products:product_list' %}"><strong>Dashboard</strong></a></li>
				<li class="breadcrumb-item active" aria-current="page"><strong>Orders</strong></li>
			</ol>
		</div>
		<!--page header-->

  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <div class="card-header bg-white">
          <div class="card-title text-dark-green">Anticipatory Orders' Histories Till Date</div>
        </div>
        <br>
        <div class="text-center">
          <h2 class="form-group text-dark-green">Filter By</h2>
        </div>

        <div class="col-md-12">
          <div class="box-element bg-dark-green" id="form-wrapper">
            <form method="get" class="form-inline text-white">
              {% for field in filtered_antiorders.form %}
                <strong>{{field.label}}:</strong>&nbsp{{field}}&nbsp&nbsp
              {% endfor %}
              <input type="submit" class="btn btn-primary" value="Go">
            </form>
          </div>
        </div>


        <div class="card-body">
          <div class="text-center">
            {% if total_antiorders > 1 %}
              <div class="form-group col-md-12">
                <h3 class="form-group text-dark-green">Total Orders: {{total_antiorders}}</h3>
              </div>
              {% else %}
              <div class="form-group col-md-12">
                <h3 class="form-group text-dark-green">Total Order: {{total_antiorders}}</h3>
              </div>
              {% endif %}
          </div>

          <div class="table-responsive">
            <table class="table card-table table-vcenter text-nowrap">
              <thead>
                <tr class="text-dark-green">
                  <th>DATE/TIME</th>
                  <th>ORDER ID</th>
                  <th>CYLINDER ID (OLD)</th>
                  <th>PRODUCT TYPE (OLD)</th>
                  <th>PRODUCT TYPE (NEW)</th>
                  <th>PRICE (OLD)</th>
                  <th>PRICE (NEW)</th>
                  <th>QUANTITY</th>
                  <th>TOTAL COST (OLD)</th>
                  <th>TOTAL COST (NEW)</th>
                  <th>PAYMENT TYPE</th>
                  <th>PAYMENT CHOICE</th>
                  <th>PAYMENT REFERENCE</th>
                  <th>PAYMENT</th>
                  <th>TRANSACTION STATUS</th>
                  <th>CYLINDER ALLOTED</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for order in antiorders_page_obj %}
                <tr class="">
                  <td>{{order.created}}</td>
                  <td>{{order.order_Id}}</td>
                  <td>{{order.product.product_Id}}</td>
                  <td>{{order.product.category.type}}({{order.product.category.mass}})</td>
                  <td>{% for order in order.cylinder.all %}{{order.category.type}}<br>{% endfor %}</td>
                  <td>₦{{order.static_price|intcomma}}</td>
                  <td>₦{% for order in order.cylinder.all %}{{order.category.price}}<br>{% endfor %}</td>
                  <td>{{order.quantity}}</td>
                  <td>₦{{order.static_total_cost|intcomma}}</td>
                  <td>₦{{order.static_total_cost2|intcomma}}</td>
                  <td>{{order.payment_type1}}{{order.payment_type2}}{{order.payment_type3}}</td>
                  <td>{{order.payment_choice}}</td>
                  <td>{{order.payment_ref}}</td>
                  <td>{{order.payment1|intcomma}} on {{order.payment1_date}}|{{order.payment2}} on {{order.payment2_date}}|{{order.payment3}} on {{order.payment3_date}}</td>
                  <td>{{order.transaction}}</td>
                  <td>{% for order in order.cylinder.all %}{{order.product_Id}}<br>{% endfor %}</td>
                  <td></td>
                  {% if order.transaction == "Closed" %}
                  <td><a href="{% url 'anticipate:show_anti_invoice' order.id %}"><button type="button" class="btn btn-sm btn-dark-green"><strong><i class="fa fa-receipt mr-1 fa-1x"></i> Invoice</strong></button></a></td>
                  {% else %}
                  <td><a href="{% url 'anticipate:show_anti_invoice_unpaid' order.id %}"><button type="button" class="btn btn-sm btn-dark-green"><strong><i class="fa fa-receipt mr-1 fa-1x"></i> Invoice</strong></button></a></td>
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <nav aria-label="...">
              <ul class="pagination justify-content-center">
                <li class="page-item"><a class="text-dark-green page-link" href="{% my_url 1 'page' request.GET.urlencode %}" tabindex="-1" aria-disabled="true">First</a></li>
                {% if antiorders_page_obj.has_previous %}
                  <li class="page-item"><a class="text-dark-green page-link" href="{% my_url antiorders_page_obj.previous_page_number 'page' request.GET.urlencode %}">{{antiorders_page_obj.previous_page_number}}</a></li>
                {% endif %}
                <li class="page-item active" aria-current="page"><a class="bg-dark-green page-link" href="{% my_url antiorders_page_obj.number 'page' request.GET.urlencode %}">{{antiorders_page_obj.number}}<span class="sr-only">(current)</span></a></li>
                {% if antiorders_page_obj.has_next %}
                  <li class="page-item"><a class="text-dark-green page-link" href="{% my_url antiorders_page_obj.next_page_number 'page' request.GET.urlencode %}">{{antiorders_page_obj.next_page_number}}</a></li>
                {% endif %}
                <li class="page-item"><a class="text-dark-green page-link" href="{% my_url antiorders_page_obj.paginator.num_pages 'page' request.GET.urlencode %}">Last</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content%}

templates/anticipate/qwikpartner_anti_order_update.html
{% extends 'board_partner.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% block title %}
  <title>Anticipatory Order Management</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}
{% load home_tags %}
<div class=" app-content">
	<div class="side-app">
    <br>
    {% include 'partials/_alerts.html' %}
		<!--Page Header-->
		<div class="page-header">
			<h4 class="page-title"><i class="fa fa-venus-mars text-dark-green mr-2 fa-1x"></i>Welcome to anticipatory orders page, <strong class="text-dark-green">{{user.first_name}}</strong></h4>
			<ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a href="{% url 'qwikpartner_board' %}"><strong>Dashboard</strong></a></li>
        <li class="breadcrumb-item"><a href="{% url 'anticipate:qwikpartner_anti_orders' %}"><strong>Anticipatory Orders</strong></a></li>
				<li class="breadcrumb-item active" aria-current="page"><strong>Update Anticipatory Order</strong></li>
			</ol>
		</div>
		<!--page header-->

    <div class="row">
      <div class="col-md-12 col-xl-12 col-lg-12">
      <div class="card">
        <form method="post" class="form-group col-lg-12 text-dark-green" enctype="multipart/form-data">
          <div class="card-header bg-white">
            <h4 class="text-dark-green">
              <i class="fas fa-clock"></i> Update Payment Status</h4>
          </div>
          <br>
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-sm-12 mb-2">
                {{ form.payment2|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-sm-12 mb-2">
                {{ form.payment2_date|as_crispy_field }}
          </div>
        </div>
        <input type="submit" class="form-group col-md-12 btn btn-cylinder" value="OK">
      </form>
      </div>
      </div>
    </div>

  </div>
</div>
{% endblock content%}