cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/cartadd/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/cartremove/<product_id>/', views.cart_remove, name='cart_remove'),

]

households/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('adm/', admin.site.urls),
    path('', include('home.urls')),
    # path('', include('pictures.urls')),
    # path('', include('videos.urls')),
    # path('', include('news.urls')),
    # path('', include('articles.urls')),
    path('', include('users.urls')),
    path('', include(('products.urls', 'products'), namespace='products')),
    path('cart', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('anticipate.urls', 'anticipate'), namespace='anticipate')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('order', views.createOrder, name='order_create'),
    path('orders', views.showOrders, name='orders'),
    path('orders/delete/<int:id>', views.deleteOrder),
    path('orders/checkout/<str:pk>/', views.showOrder, name='show_order'),
    path('orders/checkout/pay-later', views.addPayLater, name='qwikcustomer_pay_later'),
    path('orders/checkout/pay-small-small', views.addPaySmall, name='qwikcustomer_pay_small'),

    path('orders/invoice/<str:pk>/', views.showInvoice, name='show_invoice'),
    path('orders/invoice//unpaid/<str:pk>/', views.showInvoiceUnPaid, name='show_invoice_unpaid'),
    path('qwikvendor-dashboard/orders/invoice/<str:pk>/', views.showQwikVendorInvoice, name='show_vendor_invoice'),
    path('qwikpartner-dashboard/orders/invoice/<str:pk>/', views.showQwikPartnerInvoice, name='show_partner_invoice'),
    path('qwika-dashboard/orders/invoice/<str:pk>/', views.showQwikAdminInvoice, name='show_admin_invoice'),
    path('card-payment', views.showPaymentComplete, name='payment_complete'),
    path('orders/checkout/<str:pk>/pay', views.updateWallet),
    path('qwikcustomer-dashboard/orders/', views.showOrderItems, name='order_items'),
    path('qwika-dashboard/orders/', views.showQwikAdminOrders, name='qwikadmin_orders'),
    path('qwika-dashboard/credits/', views.showQwikAdminCredits, name='qwikadmin_credits'),
    path('qwika-dashboard/payments/', views.showQwikAdminPayments, name='qwikadmin_payments'),
    path('qwika-dashboard/sales/', views.showQwikAdminSales, name='qwikadmin_sales'),
    path('qwikvendor-dashboard/orders/', views.showQwikVendorOrders, name='qwikvendor_orders'),
    path('qwikvendor-dashboard/orders/update/<int:id>', views.confirmOrderVendor, name='qwikvendor_payment_status'),    
    path('qwikvendor-dashboard/order-items/', views.showQwikVendorOrderItems, name='qwikvendor_order_items'),
    path('qwikpartner-dashboard/order-items/', views.showQwikPartnerOrderItems, name='qwikpartner_order_items'),
    path('qwika-dashboard/order-items/', views.showQwikAdminOrderItems, name='qwikadmin_order_items'),
    path('qwikvendor-dashboard/order-items/add-status/<int:id>', views.addOrderStatusQwikVendor, name='qwikvendor_order_status'),
    path('qwikpartner-dashboard/order-items/add-status/<int:id>', views.addOrderStatusQwikPartner, name='qwikpartner_order_status'),
    path('qwikvendor-dashboard/order-statuses/', views.showQwikVendorOrderStatuses, name='qwikvendor_order_statuses'),
    path('qwikcustomer-dashboard/order-statuses/', views.showOrderStatuses, name='order_statuses'),
    path('qwikpartner-dashboard/order-statuses/', views.showQwikPartnerOrderStatuses, name='qwikpartner_order_statuses'),
    path('qwika-dashboard/order-statuses/', views.showQwikAdminOrderStatuses, name='qwikadmin_order_statuses'),
    path('qwikpartner-dashboard/orders/', views.showQwikPartnerOrders, name='qwikpartner_orders'),
    # path('visitor-order', views.order_visitor, name='order_visitor'),
    # path('st---only2', views.addOrder, name='add_order'),
    path('qwikcustomer-address/order/<int:id>', views.showAddressCust, name='qwikcust_address'),
    # path('qwika-dashboard/sales-graph-user/', views.showQwikAdminSalesGraphUser, name='qwikadmin_sales_graph_user'),
]

products/urls.py
from django.urls import path
from products import views
from django.contrib.sitemaps.views import sitemap
from products.sitemaps import ProductSitemap

sitemaps={
    'products':ProductSitemap,
}

urlpatterns = [
    path('products', views.product_list, name='product_list'),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('<category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<id>/', views.product_detail, name='product_detail'),
    path('product/description/<id>/', views.product_detail2, name='product_detail2'),
    path('qwikvendor-dashboard/products/', views.showQwikVendorProducts, name='qwikvendor_products'),
    path('qwikpartner-dashboard/products/', views.showQwikPartnerProducts, name='qwikpartner_products'),
    path('qwikpartner-dashboard/cylinders-received-empty/', views.showQwikPartnerCylindersReceivedEmpty, name='qwikpartner_cylinders_received_empty'),
    path('qwikvendor-dashboard/cylinders-dispatched-to-plant/', views.showQwikVendorCylindersDispatchedToPlant, name='qwikvendor_cylinders_dispatched_to_plant'),
    path('qwikvendor-dashboard/cylinders-released-filled-to-qwikpartner/', views.showQwikVendorCylindersReleasedFilledToQwikPartner, name='qwikvendor_cylinders_released_filled_to_qwikpartner'),
    path('qwikpartner-dashboard/cylinders-dispatched-filled-to-qwikcustomer/', views.showQwikPartnerCylindersDispatchedFilledToQwikCustomer, name='qwikpartner_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwika-dashboard/cylinders-dispatched-filled-to-qwikcustomer/', views.showQwikAdminCylindersDispatchedFilledToQwikCustomer, name='qwikadmin_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwikpartner-dashboard/cylinders-dispatched-filled-to-qwikcustomer/accept/<int:id>', views.acceptQwikPartnerCylindersDispatchedFilledToQwikCustomer, name='accept_qwikpartner_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwikpartner-dashboard/cylinders-dispatched-filled-to-qwikcustomer/decline/<int:id>', views.declineQwikPartnerCylindersDispatchedFilledToQwikCustomer, name='decline_qwikpartner_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwika-dashboard/cylinders-dispatched-filled-to-qwikcustomer/accept/<int:id>', views.acceptQwikAdminCylindersDispatchedFilledToQwikCustomer, name='accept_qwikadmin_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwika-dashboard/cylinders-dispatched-filled-to-qwikcustomer/decline/<int:id>', views.declineQwikAdminCylindersDispatchedFilledToQwikCustomer, name='decline_qwikadmin_cylinders_dispatched_filled_to_qwikcustomer'),
    path('qwikpartner-dashboard/cylinders-dispatched-to-plant/', views.showQwikPartnerCylindersDispatchedToPlant, name='qwikpartner_cylinders_dispatched_to_plant'),
    path('qwikpartner-dashboard/cylinders-delivered-filled-to-qwiklet/', views.showQwikPartnerCylindersDeliveredFilledToQwikLet, name='qwikpartner_cylinders_delivered_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-delivered-filled-to-qwiklet/', views.showQwikVendorCylindersDeliveredFilledToQwikLet, name='qwikvendor_cylinders_delivered_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-delivered-filled-to-qwiklet/', views.showQwikAdminCylindersDeliveredFilledToQwikLet, name='qwikadmin_cylinders_delivered_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-delivered-filled-to-qwiklet/accept/<int:id>', views.acceptQwikAdminCylindersDeliveredFilledToQwikLet, name='accept_qwikadmin_cylinders_delivered_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-delivered-filled-to-qwiklet/decline/<int:id>', views.declineQwikAdminCylindersDeliveredFilledToQwikLet, name='decline_qwikadmin_cylinders_delivered_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-delivered-filled-to-qwiklet/accept/<int:id>', views.acceptQwikVendorCylindersDeliveredFilledToQwikLet, name='accept_qwikvendor_cylinders_delivered_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-delivered-filled-to-qwiklet/decline/<int:id>', views.declineQwikVendorCylindersDeliveredFilledToQwikLet, name='decline_qwikvendor_cylinders_delivered_filled_to_qwiklet'),
    path('qwikpartner-dashboard/cylinders-returned-filled-to-qwiklet/return/<int:id>', views.returnQwikPartnerCylindersReturnedFilledToQwikLet, name='return_qwikpartner_cylinders_returned_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-returned-filled-to-qwiklet/accept/<int:id>', views.acceptQwikVendorCylindersReturnedFilledToQwikLet, name='accept_qwikvendor_cylinders_returned_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-returned-filled-to-qwiklet/decline/<int:id>', views.declineQwikVendorCylindersReturnedFilledToQwikLet, name='decline_qwikvendor_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/accept/<int:id>', views.acceptQwikAdminCylindersReturnedFilledToQwikLet, name='accept_qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/decline/<int:id>', views.declineQwikAdminCylindersReturnedFilledToQwikLet, name='decline_qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/return/<int:id>', views.returnQwikAdminCylindersReturnedFilledToQwikLet, name='return_qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/not-return/<int:id>', views.notReturnQwikAdminCylindersReturnedFilledToQwikLet, name='not_return_qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwika-dashboard/cylinders-returned-filled-to-qwiklet/', views.showQwikAdminCylindersReturnedFilledToQwikLet, name='qwikadmin_cylinders_returned_filled_to_qwiklet'),
    path('qwikpartner-dashboard/cylinders-dispatched-to-plant/accept/<int:id>', views.acceptQwikPartnerCylindersDispatchedToPlant, name='accept_qwikpartner_cylinders_dispatched_to_plant'),
    path('qwikpartner-dashboard/cylinders-dispatched-to-plant/decline/<int:id>', views.declineQwikPartnerCylindersDispatchedToPlant, name='decline_qwikpartner_cylinders_dispatched_to_plant'),
    path('qwika-dashboard/cylinders-dispatched-to-plant/', views.showQwikAdminCylindersDispatchedToPlant, name='qwikadmin_cylinders_dispatched_to_plant'),
    path('qwika-dashboard/cylinders-dispatched-to-plant/accept/<int:id>', views.acceptQwikAdminCylindersDispatchedToPlant, name='accept_qwikadmin_cylinders_dispatched_to_plant'),
    path('qwika-dashboard/cylinders-dispatched-to-plant/decline/<int:id>', views.declineQwikAdminCylindersDispatchedToPlant, name='decline_qwikadmin_cylinders_dispatched_to_plant'),
    path('qwikpartner-dashboard/cylinders-delivered-to-qwikcustomer-anticipatory/', views.showQwikPartnerCylindersDeliveredToQwikCustomerAnti, name='qwikpartner_cylinders_delivered_to_qwikcustomer_anti'),
    path('qwikpartner-dashboard/cylinders-delivered-to-qwikcustomer/', views.showQwikPartnerCylindersDeliveredToQwikCustomerUser, name='qwikpartner_cylinders_delivered_to_qwikcustomer_user'),
    path('qwikvendor-dashboard/cylinders-delivered-to-qwikcustomer/', views.showQwikVendorCylindersDeliveredToQwikCustomerUser, name='qwikvendor_cylinders_delivered_to_qwikcustomer_user'),
    path('qwikvendor-dashboard/cylinders-delivered-to-qwikcustomer-anticipatory/', views.showQwikVendorCylindersDeliveredToQwikCustomerAnti, name='qwikvendor_cylinders_delivered_to_qwikcustomer_anti'),
    path('qwika-dashboard/cylinders-delivered-to-qwikcustomer-anticipatory/', views.showQwikAdminCylindersDeliveredToQwikCustomerAnti, name='qwikadmin_cylinders_delivered_to_qwikcustomer_anti'),
    path('qwika-dashboard/cylinders-delivered-to-qwikcustomer/', views.showQwikAdminCylindersDeliveredToQwikCustomerUser, name='qwikadmin_cylinders_delivered_to_qwikcustomer_user'),
    path('qwika-dashboard/cylinders-delivered-to-qwikcustomer/update/<int:id>', views.updateQwikAdminCylindersDeliveredToQwikCustomerUser, name='update_qwikadmin_cylinders_delivered_to_qwikcustomer_user'),
    path('qwika-dashboard/cylinders-delivered-to-qwikcustomer-anticipatory/update/<int:id>', views.updateQwikAdminCylindersDeliveredToQwikCustomerAnti, name='update_qwikadmin_cylinders_delivered_to_qwikcustomer_anti'),
    path('qwikcustomer-dashboard/cylinders-received-filled-anticipatory/', views.showQwikCustomerCylindersReceivedFilledAnti, name='qwikcustomer_cylinders_received_filled_anti'),
    path('qwikcustomer-dashboard/cylinders-received-filled/', views.showQwikCustomerCylindersReceivedFilledUser, name='qwikcustomer_cylinders_received_filled_user'),
    path('qwikpartner-dashboard/cylinders-returned-filled-to-qwiklet/', views.showQwikPartnerCylindersReturnedFilledToQwikLet, name='qwikpartner_cylinders_returned_filled_to_qwiklet'),
    path('qwikvendor-dashboard/cylinders-returned-filled-to-qwiklet/', views.showQwikVendorCylindersReturnedFilledToQwikLet, name='qwikvendor_cylinders_returned_filled_to_qwiklet'),
    path('qwikpartner-dashboard/cylinders-returned-empty/', views.showQwikPartnerCylindersReturnedEmpty, name='qwikpartner_cylinders_returned_empty'),
    path('qwikvendor-dashboard/cylinders-returned-empty/', views.showQwikVendorCylindersReturnedEmpty, name='qwikvendor_cylinders_returned_empty'),
    path('qwikvendor-dashboard/cylinders-returned-empty/accept/<int:id>', views.acceptQwikVendorCylindersReturnedEmpty, name='accept_qwikvendor_cylinders_returned_empty'),
    path('qwikvendor-dashboard/cylinders-returned-empty/decline/<int:id>', views.declineQwikVendorCylindersReturnedEmpty, name='decline_qwikvendor_cylinders_returned_empty'),
    path('qwika-dashboard/cylinders-returned-empty/accept/<int:id>', views.acceptQwikAdminCylindersReturnedEmpty, name='accept_qwikadmin_cylinders_returned_empty'),
    path('qwika-dashboard/cylinders-returned-empty/decline/<int:id>', views.declineQwikAdminCylindersReturnedEmpty, name='decline_qwikadmin_cylinders_returned_empty'),

templates/orders/create0.html
{% extends 'board.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% load humanize %}
{% block title %}
  <title>Complete Order</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}
<div class=" app-content">
	<div class="side-app">
    <br>
    {% include 'partials/_alerts.html' %}
    <div class="form-group col-md-12 mt-2">
      <div class="card col-md-12">
        <form method="post" class="form-group text-dark-green" enctype="multipart/form-data">
          <div class="card-header bg-white">
            <h4 class="text-cylinder">
              <i class="fas fa-list"></i> Your Order Summary</h4>
          </div>
          {% csrf_token %}

          <div class="">
              <h3></h3>
              <ul class="text-cylinder">
                  {% for item in cart %}
                    <div class="row">
                      <div class="col-md-5">
                        <strong class="text-dark-green">From Outlet:</strong> <li>{{item.outlet_o}}</li>
                        <strong class="text-dark-green">To Address:</strong> <li>{{item.address_o}}</li>
                        <br>
                        <br>
                      </div>
                      <div class="col-md-5">
                        <li>{{ item.quantity }} x {{ item.product.category.type }} = <span>₦{{ item.total_price|intcomma }}</span></li>
                        <br>
                      </div>
                    </div>
                  {% endfor %}
                  <div class="row">
                    <div class="col-md-5">

                    </div>
                    <div class="col-md-5">
                      <p class="text-dark-green"><strong>Total: ₦{{ cart.get_total_price|intcomma }}</strong></p>
                    </div>
                  </div>

              </ul>

          </div>
          {{form.media}}
          {{form|crispy}}
          <input type="submit" class="form-group col-md-12" value="Complete Order">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

templates/orders/invoice.html
{% extends 'board.html' %}
{% load static %}
{% load humanize %}
{% block title %}
  <title>Orders</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}

{% load home_tags %}
<div class=" app-content">
	<div class="side-app">
    <br>
    {% include 'partials/_alerts.html' %}
		<!--Page Header-->
		<div class="page-header">
			<h4 class="page-title"><i class="fa fa-receipt text-dark-green mr-2 fa-1x"></i>Welcome to your invoice page, <strong class="text-dark-green">{{user.first_name}}</strong></h4>
			<ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a href="{% url 'products:product_list' %}"><strong>Dashboard</strong></a></li>
				<li class="breadcrumb-item active" aria-current="page"><strong>Invoice</strong></li>
			</ol>
		</div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="d-flex">
              <a class="header-brand" href="index.html">
                <img alt="logo" class="logo2" src="{% static 'img/logo.png' %}">
              </a>

              <div class="text-right ml-auto">
                <h2 class="mb-1 text-dark-green">Invoice {{order.order_Id}}</h2>
                <p class="mb-1"><span class="font-weight-semibold">Invoice Date:</span> {{order.created}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-lg-6 ">
                <p class="h3 text-dark-green">Invoice From:</p>
                <address>
                  {{order.outlet}} Outlet<br>
                  {{order.outlet.address}}<br>
                  {{order.outlet.email}}
                </address>
              </div>
              <div class="col-lg-6 text-right">
                <p class="h3 text-dark-green">Invoice To:</p>
                <address>
                  {{order.user.first_name}} {{order.user.last_name}}<br>
                  {{order.user.com_name}}<br>
                  {{order.user.address}}<br>
                  {{order.user.email}}
                </address>
              </div>
            </div>
            <div class="table-responsive push">
              <table class="table card-table table-vcenter text-nowrap">
                <tr class=" ">
                  <th class="text-dark-green"><strong>Product</strong></th>
                  <th class="text-dark-green"><strong>Quantity</strong></th>
                  <th class="text-right text-dark-green"><strong>Unit Price</strong></th>
                  <th class="text-right text-dark-green"><strong>Sub Total</strong></th>
                </tr>
                {% for order_item in order_items %}
                <tr>
                  <td>
                    <p class="font-w600 mb-1">{{order_item.product.category}}</p>
                    <div class="text-muted"><div class="text-muted">{{order_item.product.category.description}}</div></div>
                  </td>
                  <td class="num-font">{{order_item.quantity}}</td>
                  <td class="text-right num-font">₦{{order_item.product.category.price|intcomma}}</td>
                  <td class="text-right num-font">₦{{order_item.get_cost|intcomma}}</td>
                </tr>
                {% endfor %}
                <tr>
                  <td colspan="3" class="font-weight-bold text-uppercase text-right text-dark-green">Total</td>
                  <td class="font-weight-bold text-right num-font text-dark-green">₦{{order.get_total_cost|intcomma}}</td>
                </tr>
              </table>
            </div>
          </div>
          <div class="card-footer text-right">
            <img alt="Stamp" class="logo" src="{% static 'img/paid.png' %}">
            <br>
            <button type="button" class="btn btn-cylinder mb-1" onClick="javascript:window.print();"><i class="fas fa-print fa-1x mr-1"></i> Print Invoice</button>
          </div>
        </div>
      </div>
    </div>
  </div>



	</div>
  </div>
{% endblock content%}

templates/orders/invoice_unpaid.html
{% extends 'board.html' %}
{% load static %}
{% load humanize %}
{% block title %}
  <title>Orders</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}

{% load home_tags %}
<div class=" app-content">
	<div class="side-app">
    <br>
    {% include 'partials/_alerts.html' %}
		<!--Page Header-->
		<div class="page-header">
			<h4 class="page-title"><i class="fa fa-receipt text-dark-green mr-2 fa-1x"></i>Welcome to your invoice page, <strong class="text-dark-green">{{user.first_name}}</strong></h4>
			<ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a href="{% url 'products:product_list' %}"><strong>Dashboard</strong></a></li>
				<li class="breadcrumb-item active" aria-current="page"><strong>Invoice</strong></li>
			</ol>
		</div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="d-flex">
              <a class="header-brand" href="index.html">
                <img alt="logo" class="logo2" src="{% static 'img/logo.png' %}">
              </a>

              <div class="text-right ml-auto">
                <h2 class="mb-1 text-dark-green">Invoice {{order.order_Id}}</h2>
                <p class="mb-1"><span class="font-weight-semibold">Invoice Date:</span> {{order.created}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-lg-6 ">
                <p class="h3 text-dark-green">Invoice From:</p>
                <address>
                  {{order.outlet}} Outlet<br>
                  {{order.outlet.address}}<br>
                  {{order.outlet.email}}
                </address>
              </div>
              <div class="col-lg-6 text-right">
                <p class="h3 text-dark-green">Invoice To:</p>
                <address>
                  {{order.user.first_name}} {{order.user.last_name}}<br>
                  {{order.user.com_name}}<br>
                  {{order.user.address}}<br>
                  {{order.user.email}}
                </address>
              </div>
            </div>
            <div class="table-responsive push">
              <table class="table card-table table-vcenter text-nowrap">
                <tr class=" ">
                  <th class="text-dark-green"><strong>Product</strong></th>
                  <th class="text-dark-green"><strong>Quantity</strong></th>
                  <th class="text-right text-dark-green"><strong>Unit Price</strong></th>
                  <th class="text-right text-dark-green"><strong>Sub Total</strong></th>
                </tr>
                {% for order_item in order_items %}
                <tr>
                  <td>
                    <p class="font-w600 mb-1">{{order_item.product.category}}</p>
                    <div class="text-muted"><div class="text-muted">{{order_item.product.category.description}}</div></div>
                  </td>
                  <td class="num-font">{{order_item.quantity}}</td>
                  <td class="text-right num-font">₦{{order_item.product.category.price|intcomma}}</td>
                  <td class="text-right num-font">₦{{order_item.get_cost|intcomma}}</td>
                </tr>
                {% endfor %}
                <tr>
                  <td colspan="3" class="font-weight-bold text-uppercase text-right text-dark-green">Total</td>
                  <td class="font-weight-bold text-right num-font text-dark-green">₦{{order.get_total_cost|intcomma}}</td>
                </tr>
              </table>
            </div>
          </div>
          <div class="card-footer text-right">
            <button type="button" class="btn btn-cylinder mb-1" onClick="javascript:window.print();"><i class="fas fa-print fa-1x mr-1"></i> Print Invoice</button>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock content%}

templates/orders/qwikpartner_order_items_update.html
{% extends 'board_partner.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% block title %}
  <title>Order Items Management</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}
{% load home_tags %}
<div class=" app-content">
	<div class="side-app">
    <br>
    {% include 'partials/_alerts.html' %}
		<!--Page Header-->
		<div class="page-header">
			<h4 class="page-title"><i class="fa fa-venus-mars text-dark-green mr-2 fa-1x"></i>Welcome to new orders page, <strong class="text-dark-green">{{user.first_name}}</strong></h4>
			<ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a href="{% url 'qwikpartner_board' %}"><strong>Dashboard</strong></a></li>
        <li class="breadcrumb-item"><a href="{% url 'orders:qwikpartner_orders' %}"><strong>Orders</strong></a></li>
        <li class="breadcrumb-item"><a href="{% url 'orders:qwikpartner_order_items' %}"><strong>Order Itmes (New)</strong></a></li>
				<li class="breadcrumb-item active" aria-current="page"><strong>Update Order Item</strong></li>
			</ol>
		</div>
		<!--page header-->

    <div class="row">
      <div class="col-md-12 col-xl-12 col-lg-12">
      <div class="card">
        <form method="post" class="form-group col-lg-12 text-dark-green" enctype="multipart/form-data">
          <div class="card-header bg-cylinder">
            <h4 class="text-white">
              <i class="fas fa-clock"></i> Update Order Item Status</h4>
          </div>
          <br>
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-sm-12 mb-2">
                {{ form.cylinder|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-12 mb-2">
                {{ form.order_status|as_crispy_field }}
            </div>
        </div>
        <input type="submit" class="form-group col-md-12 btn btn-cylinder" value="OK">
      </form>
      </div>
      </div>
    </div>

  </div>
</div>
{% endblock content%}